In [2]:
import numpy as np

In [ ]:
# Create a 1D array, apply some properties and methods to it
arr = np.array([1, 2, 3, 4, 5],ndmin=1)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.itemsize)
print(arr.data)
print(arr.strides)
print(arr.flags)
print(arr.nbytes)
print(arr.base)
print(arr.ctypes)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32
(5,)
5
1
4
(4,)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

20
None


In [17]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.shape)
print(arr2d.strides)
print(arr2d.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
(12, 4)
int32


In [24]:
dt = np.dtype([('aget',np.int8)])
arr3 = np.array([(10,),(20,),(30,)],dtype=dt)
print(arr3)
print(arr3['aget'])
print(dt.type)

[(10,) (20,) (30,)]
[10 20 30]
<class 'numpy.void'>


In [ ]:
# in the example blow, convert the data type of the array from int to float
real_data = np.array([10,20,30,40,50], dtype=np.int32)
print(real_data)
print(real_data.dtype)

cast_data = real_data.astype(np.float16)
print(cast_data)
print(cast_data.dtype)

[10 20 30 40 50]
int32
[10. 20. 30. 40. 50.]
float16


In [ ]:
# in the example below, convert the data type of the array from float to int
float_data = np.array([10.1,20.2,30.3,40.4,50.5], dtype=np.float16)
print(float_data)
print(float_data.dtype)

int_data = np.int8(float_data)
print(int_data)
print(int_data.dtype)

[10.1 20.2 30.3 40.4 50.5]
float16
[10 20 30 40 50]
int8


In [35]:
# in the example below, convert the data type of the array from string to int
string_data = np.array(['2.2','78.5','three','four','111'])
print(string_data)
print(string_data.dtype)

def string_to_nan(data):
    result = []
    for item in data:
        try:
            result.append(float(item))
        except:
            result.append(np.nan)
    return np.array(result)

string_to_float = string_to_nan(string_data)
print(string_to_float)
print(string_to_float.dtype)      

['2.2' '78.5' 'three' 'four' '111']
<U5
[  2.2  78.5   nan   nan 111. ]
float64


In [ ]:
#generate a 2D array with random values
zeros_arr = np.zeros([5,4])
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# generate a 2D array with ones
ones_arr = np.ones((5,4),dtype=np.float16, order='F')
print(ones_arr)
print(ones_arr.dtype)  

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float16


In [ ]:
# arange() function is used to generate a sequence of numbers
list1 = np.arange(1,11)
print(list1)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
squence_num, step = np.linspace(1,2, num=10, endpoint=True, retstep=True)
print(squence_num)
print("Step size: ", step)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
Step size:  0.1111111111111111


In [ ]:
# generate a random 2D array   
random_arr = np.random.rand(2,3)
print(random_arr)

[[0.21777244 0.16762774 0.38300416]
 [0.40452458 0.43298339 0.90552592]]


In [ ]:
# generate an empty 2D array
empty_arr = np.empty((2,3))
print(empty_arr)    

[[0.21777244 0.16762774 0.38300416]
 [0.40452458 0.43298339 0.90552592]]


In [ ]:
# generate a full 2D array
full_arr = np.full((3,3),7)
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# Array manipulation functions

Changing shape

In [ ]:
# reshape() function is used to change the shape of the array
arr = np.arange(8)
print(arr)

# reshape the array
arr_reshaped = arr.reshape(4,2)
print(arr_reshaped)

# one another way to reshape the array
arr_reshaped2 = np.reshape(arr,(2,4))
print(arr_reshaped2)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [75]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)


# flatten() function is used to convert a 2D array into 1D array
for item in arr2d.flat:
    print(item, end=' ')
print()
for index, value in enumerate(arr2d.flat): 
    arr2d.flat[index] = value * 2 # multiply each element by 2
print(arr2d)

[[1 2 3]
 [4 5 6]]
1 2 3 4 5 6 
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6]])
print("Original array: ", arr2d)

# flatten the array
flattened_arr = arr2d.flatten(order='F')
print("Flattened array: ", flattened_arr)

Original array:  [[1 2 3]
 [4 5 6]]
Flattened array:  [1 4 2 5 3 6]


In [84]:
arr2d = np.array([[1,2,3],[4,5,6]])
print("Original array: ", arr2d)

flattened_array = np.ravel(arr2d)
print("Flattened array: ", flattened_array)

Original array:  [[1 2 3]
 [4 5 6]]
Flattened array:  [1 2 3 4 5 6]


Transpose Operations

In [89]:
arr = np.array([[1,2,3],[4,5,6]])
print("Original array: ")
print(arr)

# transpose the array
transposed_arr = np.transpose(arr)
print("Transposed array: ")
print(transposed_arr)

# another way to transpose the array
transposed_arr2 = arr.T
print("Another way to transpose the array: ")
print(transposed_arr2)

Original array: 
[[1 2 3]
 [4 5 6]]
Transposed array: 
[[1 4]
 [2 5]
 [3 6]]
Another way to transpose the array: 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.arange(24).reshape(2,3,4)
print(a)

# rollaxis() function is used to roll the specified axis backwards
result = np.rollaxis(a,2,0)
print(result)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


Changing Dimensions

In [102]:
arr1 = np.array([1,2,3])
arr2 = np.array([[10],[20],[30]])
broadcasted_arr = np.broadcast(arr1,arr2)
print(broadcasted_arr.shape)
for x,y in broadcasted_arr:
    print(f"({x},{y})")

(3, 3)
(1,10)
(2,10)
(3,10)
(1,20)
(2,20)
(3,20)
(1,30)
(2,30)
(3,30)
