In [1]:
import numpy as np

In [4]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1.strides)

(12, 4)


In [5]:
print(arr1.shape)
print(arr1.strides)

(2, 3)
(12, 4)


In [16]:
dt = np.dtype('i8')
print(dt)

int64


In [21]:
zero_arr = np.zeros((2,5), dtype=np.int32)
print(zero_arr)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [23]:
list1 = np.arange(1,10, dtype=np.float16)
print(list1)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [28]:
list2, step = np.linspace(1,2, num=10, endpoint=True, retstep=True)
print(list2)
print(step)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
0.1111111111111111


In [38]:
list1 = np.eye(N=5, M=None, k=-2, dtype=int)
print(list1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [39]:
list1 = np.identity(5, dtype=int)
print(list1)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [44]:
arr = np.array([[12,13,14], [15,16,17], [18,19,20]])
print(arr)
diagnol_arr = np.diag(arr, k=0)
print(diagnol_arr)

[[12 13 14]
 [15 16 17]
 [18 19 20]]
[12 16 20]


In [46]:
def fun(x,y):
    return x * y
arr = np.fromfunction(fun, (3,3), dtype=int)
print(arr)


[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [52]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
new_arr = np.pad(arr, pad_width=2, mode='constant')
print(new_arr)

[[1 2 3]
 [4 5 6]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
